from environment.ma_gym.multi_agent_gym_environment import MultiAgentGymEnvironment
from rendering.ma_gym.multi_agent_gym_renderer import MultiAgentGymRenderer
from solver.ma_gym.multi_agent_gym_solver import MultiAgentGymSolver
from utils.training_evaluation_pipeline import execute_replay_policy_comparison

environment = MultiAgentGymEnvironment(env_to_load='ma_gym:PredatorPrey7x7-v0')
renderer = MultiAgentGymRenderer(environment)
renderer.set_sleep_time(0.1)
execute_replay_policy_comparison(environment, MultiAgentGymSolver, renderer)
